copy image to current folder when pasting image from the clipboard
XmacsLabs/mogan pull request #121
Opened 2022-04-02 04:13 UTC by PikachuHy

## Overview

Give an option like Typora,

![image](https://user-images.githubusercontent.com/18223871/161365467-d6f97015-ea93-483f-a5d4-5a463be77f01.png)

But now, only support `copy image to current folder`.

## How to test
add the following scheme code to your `init-buffer.scm`

```scm
(define (notify-julia-syntax2 var val)
  ())

(define-preferences
  ("copy image to current folder" "on" notify-julia-syntax2))
```
Is there a more elegant way to change user preferences? 😭

## Why

I just want to provide an option
separate binary data and plain text.

## snapshot

![image](https://user-images.githubusercontent.com/18223871/161365829-5d3f5686-3da0-41a0-814e-12dd1a0d6eb3.png)

2022-04-02 13:47 UTC, darcy-shen commented
#118 also needs a option in the preference. Well, I think it is ok to impl the feature first and then add the preferences.

2022-04-02 16:10 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +    auto img = qvariant_cast<QImage>(md->imageData());
it is ok to use C++11 syntax in Mogan.

2022-04-03 11:23 UTC, PikachuHy commented
?

2022-04-03 14:52 UTC, darcy-shen commented
I have to test it locally on my laptop. Yesterday, I just reviewed the code.

2022-04-03 15:04 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +      QString cur_time_str = QDateTime::currentDateTime().toString("yyyyMMddhhmmsszzzddd");
<img width="229" alt="image" src="https://user-images.githubusercontent.com/1267865/161434324-4c6baf4e-b610-4bbf-9b5b-ff8f375ad703.png">

I'm using the Chinese locale, is it the expected file name?

2022-04-03 15:05 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +    QImage img = qvariant_cast<QImage>(md->imageData());
please use jolly style

2022-04-03 15:07 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
if the current buffer is the no name file, we will save the image to `$TEXMACS_HOME_PATH/texts/scratch`

2022-04-03 15:10 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +        // insert raw data if fail
Use debug_io to print out the `tmp_image_path` here?

It should happen really rarely.

2022-04-03 15:11 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
If the current buffer is the immutable doc file, I think we will fail to save it to the corresponding folder.

2022-04-03 15:14 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
<img width="588" alt="image" src="https://user-images.githubusercontent.com/1267865/161434775-144e2b11-5fd1-41fc-9614-8faa6e60c995.png">

And sometimes, the current buffer is actually a tmfs path.

2022-04-03 15:16 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
For remote files, the current files are using http/https protocal:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1267865/161434834-d9e35a42-a0f7-4281-8aea-544a5e666eec.png">

2022-04-03 15:17 UTC, darcy-shen requested changes
If a pr is not ready to be reviewed, just mark it as draft. I've just marked your cmake pr as draft.

2022-04-04 14:22 UTC, PikachuHy commented on src/Plugins/Qt/qt_gui.cpp
> +      QString cur_time_str = QDateTime::currentDateTime().toString("yyyyMMddhhmmsszzzddd");
no, I will remove `ddd`

2022-04-04 14:40 UTC, PikachuHy commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
> the current buffer is actually a tmfs path.

```
bool ok= img.save (tmp_image_path);
```
`img.save` will return false.

So, we will insert raw data

2022-04-04 15:14 UTC, PikachuHy commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
> If the current buffer is the immutable doc file (doc files under $TEXMACS_HOME), I think we will fail to save it to the corresponding folder.

How to test that?

if saving images fail, we will insert raw data.

2022-04-05 02:08 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
just test if a URL is starting with $TEXMACS_HOME

2022-04-05 02:54 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +      string doc_path = as_string(get_current_buffer());
See #132 , if you are not familiar with the API, add unit tests for them first.

2022-04-05 02:58 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +    if (starts (doc_path, "tmfs://")
``` cpp
need_save_image = (pref == "on") && !is_rooted_web(url) && !is_rooted_tmfs(url) && descends(url, url_system("$TEXMACS_PATH"))
```

2022-04-05 06:06 UTC, darcy-shen commented on src/Plugins/Qt/qt_gui.cpp
> +        && descends (doc_url, url_system ("$TEXMACS_PATH"))) {
!descends

doc_url should not start with $TEXMACS_PATH

2022-04-05 12:04 UTC, darcy-shen approved these changes
manually tested on GNU/Linux

2022-04-05 12:04 UTC, merged