[29_3] Modify the way users choose whether to embed tm into pdf
XmacsLabs/mogan pull request #1248
Opened 2023-10-11 08:08 UTC by tangdouer1005

Before the modification, the option in the preference was used to control whether the exported PDF should be embedded with tm document.
the disadvantage of this method is that it is inconvenient for users.because one would like to leave to the user to choose either to embed or not for each document. 
So I deleted the option in preference and added iterm to menu to control whether to embed or not.

2023-10-11 08:43 UTC, darcy-shen commented on src/Edit/editor.hpp
> +  virtual bool attach_doc_to_exported_pdf (url pdf_name) = 0;
please use scheme to implement it

2023-10-11 08:44 UTC, darcy-shen commented on TeXmacs/progs/texmacs/texmacs/tm-print.scm
> +(tm-define (wrapped-print-to-pdf-embeded-with-tm fname)
use `use-plugin-pdf?` to see if pdf plugin is supported

2023-10-11 09:17 UTC, tangdouer1005 commented on src/Edit/editor.hpp
> +  virtual bool attach_doc_to_exported_pdf (url pdf_name) = 0;
ok

2023-10-14 17:03 UTC, mgubi requested changes

2023-10-16 09:57 UTC, mgubi approved these changes

2023-10-16 11:20 UTC, darcy-shen commented on src/Texmacs/Data/new_buffer.cpp
> +    // if the saving fime is a pdf, embed the tm into pdf
typo: fime -> format

2023-10-16 12:01 UTC, darcy-shen commented on TeXmacs/progs/texmacs/texmacs/tm-print.scm
> +        (unless(attach-doc-to-exported-pdf fname)
put a space after unless

2023-10-16 12:01 UTC, darcy-shen commented on TeXmacs/progs/texmacs/texmacs/tm-print.scm
> +      (unless(attach-doc-to-exported-pdf fname)
put a space after unless

2023-10-16 12:02 UTC, darcy-shen commented on TeXmacs/progs/texmacs/texmacs/tm-print.scm
> +          (notify-now "fail to attach tm to pdf")))))
fail -> Fail

An error message starting with upcased letter would be better

2023-10-17 05:13 UTC, merged