support Safari-like tab
XmacsLabs/mogan pull request #142
Opened 2022-04-06 10:47 UTC by PikachuHy

https://github.com/XmacsLabs/mogan/issues/4

> tabs like firefox tabs for document management

## FIXME

- document changes are not smooth

although using the same API as `go-menu`

```
call ("switch-to-buffer*", object (m_buffers[index]));
```

## snapshot

![image](https://user-images.githubusercontent.com/18223871/161958240-bf8a9610-03ab-42a8-8531-da2fe57c576d.png)

2022-04-06 12:28 UTC, darcy-shen commented on src/Plugins/Qt/DocTabBar.h
> +// Created by PikachuHy on 2022/4/6.
same above

2022-04-06 12:32 UTC, darcy-shen commented on src/Plugins/Qt/DocTabBar.h
> +class DocTabBar : public QTabBar {
The name convention should be QTMDocTabBar

2022-04-06 12:59 UTC, YiqiXu commented
Once this PR is merged, issue #60 can be closed.

2022-04-06 13:23 UTC, YiqiXu commented
Is it controlled by the following option?

<img width="703" alt="image" src="https://user-images.githubusercontent.com/32867606/161984649-01fe5be3-5fa9-428d-acd6-fd3778e2395c.png">

2022-04-06 14:08 UTC, darcy-shen commented
> Do the following options control it? Or should we add another option like "Multiple documents in tabs"?

Let's merge the existing code first and then we can improve it step by step. Just cannot wait to use it!

2022-04-07 11:47 UTC, darcy-shen requested changes
Please follow the class name convention of the original GNU TeXmacs. The reason is that we'd better contribute this pull request back to GNU TeXmacs.

2022-04-07 12:23 UTC, PikachuHy commented
warning

this feature may cause the Qt6 version TeXmacs to throw an exception.

weird

2022-04-07 12:44 UTC, darcy-shen approved these changes
LGTM

2022-04-07 12:44 UTC, merged