[66_5] Perf tuning on tm_reader::decode
XmacsLabs/mogan pull request #1649
Opened 2024-02-15 16:44 UTC by darcy-shen

## Why you open this Pull Request?

## What work have you done in the current Pull Request?
For 5m tm doc: `564ms -> 543ms`

2024-02-16 01:35 UTC, jingkaimori requested changes
further optimization can be done, and qtest has facilities for benchmark:

https://doc.qt.io/qt-6/qttestlib-tutorial5-example.html

2024-02-16 01:35 UTC, jingkaimori commented on src/Data/Convert/Texmacs/fromtm.cpp
>      if (((i + 1) < n) && (s[i] == '\\')) {
```suggestion

  int    n= N (s);
  int start= index_of (s, '\\');
  if (start == -1 || start == n-1) return s;

  string r= s (0, start);
  for (int i= start; i < n; i++)
    if (s[i] == '\\') {
```

2024-02-16 06:40 UTC, darcy-shen commented
> and qtest has facilities for benchmark:

we do no need micro bench here.

2024-02-16 06:48 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
>      if (((i + 1) < n) && (s[i] == '\\')) {
这个代码有问题，原本的代码是正确的

2024-02-16 06:50 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
>      if (((i + 1) < n) && (s[i] == '\\')) {
s里面如果有两个\，然后第二个\正好在最后，那么会出现i++之后i==n，这样数组越界了。

2024-02-16 09:03 UTC, darcy-shen commented
Tested on Linux, there is no significant performance improvements.

2024-02-16 09:57 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
> +  for (; i < n_minus_one; i++)
直接用n-1就可以了

2024-02-16 10:01 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
> +  if (i < n) {
这里需要说明一下为什么要这样，增加一个单元测试覆盖 i=n 这种情况

2024-02-16 10:18 UTC, jingkaimori commented
Performance is slightly improved:

Before:
```
PASS   : TestConverter::test_texmacs_to_tree_bench(29_1_1.tm)
RESULT : TestConverter::test_texmacs_to_tree_bench():"29_1_1.tm":
     0.018 msecs per iteration (total: 76, iterations: 4096)
PASS   : TestConverter::test_texmacs_to_tree_bench(46_3.tm)
RESULT : TestConverter::test_texmacs_to_tree_bench():"46_3.tm":
     0.394 msecs per iteration (total: 101, iterations: 256)
PASS   : TestConverter::test_texmacs_to_tree_bench(64_1.tm)
RESULT : TestConverter::test_texmacs_to_tree_bench():"64_1.tm":
     1.5 msecs per iteration (total: 98, iterations: 64)
```

After:
```
PASS   : TestConverter::test_texmacs_to_tree_bench(29_1_1.tm)
RESULT : TestConverter::test_texmacs_to_tree_bench():"29_1_1.tm":
     0.016 msecs per iteration (total: 69, iterations: 4096)
PASS   : TestConverter::test_texmacs_to_tree_bench(46_3.tm)
RESULT : TestConverter::test_texmacs_to_tree_bench():"46_3.tm":
     0.37 msecs per iteration (total: 95, iterations: 256)
PASS   : TestConverter::test_texmacs_to_tree_bench(64_1.tm)
RESULT : TestConverter::test_texmacs_to_tree_bench():"64_1.tm":
     1.4 msecs per iteration (total: 92, iterations: 64)
```

2024-02-16 10:24 UTC, jingkaimori commented on src/Data/Convert/Texmacs/fromtm.cpp
> +  for (; i < n_minus_one; i++)
这么写循环里还能少一条指令

2024-02-16 11:21 UTC, jingkaimori approved these changes
LGTM

2024-02-27 15:13 UTC, jingkaimori commented
Modification should not be make on parser of tm. tmu parser needs these optimization.

2024-02-27 15:13 UTC, closed without merging