[75_21] Upgrade to lolly 1.3.16 and moebius 0.1.16
XmacsLabs/mogan pull request #1742
Opened 2024-03-20 16:41 UTC by darcy-shen

2024-03-20 17:21 UTC, darcy-shen commented on tests/Graphics/Mathematics/math_test.cpp
> +  // QCOMPARE (as_tree (exp (v)), tree (TUPLE, as_tree (exp (1.0)),
do not know why it does not work

2024-03-21 00:03 UTC, Oyyko commented on tests/Graphics/Mathematics/math_test.cpp
> +  // QCOMPARE (as_tree (exp (v)), tree (TUPLE, as_tree (exp (1.0)),
what's the output of `as_tree (exp (v))` and `tree (TUPLE, as_tree (exp (1)),
                                     as_tree (exp (2)), as_tree (exp (3)))`.

2024-03-21 06:25 UTC, darcy-shen commented on tests/Graphics/Mathematics/math_test.cpp
> +  // QCOMPARE (as_tree (exp (v)), tree (TUPLE, as_tree (exp (1.0)),
well, it is a float number issue

2024-03-21 06:49 UTC, jingkaimori commented on tests/Graphics/Mathematics/math_test.cpp
> +  // QCOMPARE (as_tree (exp (v)), tree (TUPLE, as_tree (exp (1.0)),
there is a float-point precision lost here. execute such statements in test:
```cpp
cout << (v[1] == 2.0) << LF;
  cout << (exp (v)[1] == exp (v[1])) << LF;
  cout << (exp (v)[1] == exp_op::op (v[1])) << LF;
```
Output is:
```
true
false
false
```

2024-03-21 06:57 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
> +      else if ((s[i] >= '@') && (s[i] < '`')) r << as_string (s[i] - '@');
这一行可能是导致`17_1.scm`失败的原因

2024-03-21 07:03 UTC, jingkaimori commented on tests/Graphics/Mathematics/math_test.cpp
> +  // (2.0)), as_tree (exp (3.0))));
```suggestion
QCOMPARE (as_tree (log (v)), tree (TUPLE, as_tree (log (1.0)),
                                     as_tree (log (2.0)), as_tree (log (3.0))));;
```
use log instead of exp can reduce such problem

2024-03-21 07:04 UTC, jingkaimori commented on src/Data/Convert/Texmacs/fromtm.cpp
> +      else if ((s[i] >= '@') && (s[i] < '`')) r << as_string (s[i] - '@');
agree

2024-03-21 07:15 UTC, darcy-shen commented on tests/Graphics/Mathematics/math_test.cpp
> +  // (2.0)), as_tree (exp (3.0))));
这现在把代码注释掉没有区别

2024-03-21 07:20 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
> +      else if ((s[i] >= '@') && (s[i] < '`')) r << as_string (s[i] - '@');
```
Process 12591 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100dcdc44 MoganResearch`bool lolly::data::operator<=<char>(lolly::data::lolly_string_view<char> const&, lolly::data::lolly_string_view<char> const&) + 136
```

2024-03-21 07:27 UTC, jingkaimori commented
也许lolly里加一个直接从string_view构造tree的构造函数会更好

2024-03-21 07:42 UTC, darcy-shen commented
> 也许lolly里加一个直接从string_view构造tree的构造函数会更好

string_view不安全，用在接口中本身不合适

2024-03-21 07:43 UTC, jingkaimori commented on src/Data/Convert/Texmacs/fromtm.cpp
> +      else if ((s[i] >= '@') && (s[i] < '`')) r << as_string (s[i] - '@');
```suggestion
      else if ((s[i] >= '@') && (s[i] < '`')) r << (char) (s[i] - '@');
```

2024-03-21 07:58 UTC, jingkaimori commented
> string_view不安全，用在接口中本身不合适

构造树的时候复制view里面的字符串就可以了，view只是不能作为持久化数据结构的成员或者是非局部变量，当然可以作为函数参数

2024-03-21 08:15 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
> +      else if ((s[i] >= '@') && (s[i] < '`')) r << as_string (s[i] - '@');
这个建议修改并不能修复这个bug，添加日志后，发现crash的不在这块

2024-03-21 08:28 UTC, jingkaimori requested changes
Some suggestions to this pr.

Changes expected in lolly:

* Construct tree from string_view;
* A alias for `lolly::data::lolly_string_view<char>`;
* User-defined string literal of string_view, like `"string"v`.
    * behaves like [`operator""sv`](https://zh.cppreference.com/w/cpp/string/basic_string_view/operator%22%22sv)
    * following code can be valid:
      ```cpp
      string s = condition ? "true str"v : "false str"v;
      ```

2024-03-21 08:34 UTC, jingkaimori commented on src/Data/Convert/Texmacs/fromtm.cpp
> +      else if ((s[i] >= '@') && (s[i] < '`')) r << as_string (s[i] - '@');
所有末尾追加字符的`<<`操作符改得都有点问题，都改成了字符转字符码再连接了。按照下面的review改完，12_1就能过了

2024-03-21 08:46 UTC, darcy-shen commented on src/Graphics/Renderer/printer.cpp
> +    string root= (pos == -1 ? fn_name : string (fn_name (0, pos)));
这个是必须要改，还是为了增强性能？

2024-03-21 08:47 UTC, jingkaimori commented on src/Graphics/Renderer/printer.cpp
> +    string root= (pos == -1 ? fn_name : string (fn_name (0, pos)));
目前可以不改，是增强性能

2024-03-21 08:55 UTC, darcy-shen commented on src/Data/Convert/Texmacs/fromtm.cpp
> +      else if ((s[i] >= '@') && (s[i] < '`')) r << as_string (s[i] - '@');
这里是cork encoding，这个建议是对的。

2024-03-21 09:09 UTC, darcy-shen commented
> A alias for lolly::data::lolly_string_view<char>;

这个是需要的，另外两个我觉得没有必要

2024-03-21 09:25 UTC, darcy-shen commented
> User-defined string literal of string_view, like "string"v

这个没必要，因为代码一样要改

2024-03-21 09:27 UTC, darcy-shen commented
> 构造树的时候复制view里面的字符串就可以了，view只是不能作为持久化数据结构的成员或者是非局部变量，当然可以作为函数参数

这点我赞同，这个pr可以变得小一些

2024-03-21 14:43 UTC, jingkaimori commented
https://github.com/XmacsLabs/mogan/blob/b6aad86b90f28f7c7cc877bb9298de1ce2678e90/src/Data/Convert/Texmacs/totm.cpp#L166

这里也得改：
```cpp
        else if (((unsigned char) c) < ' ') tmp << '\\' << (char) (c + '@');
```

2024-03-21 15:28 UTC, darcy-shen commented
> 这里也得改：

为什么不能和原来一样，自动转成 char

2024-03-21 16:43 UTC, closed without merging