[70_2] AST Syntax Highlighting for C++
XmacsLabs/mogan pull request #1993
Opened 2024-08-07 04:54 UTC by UnbSky

## What
Use xmake to import tree-sitter and tree-sitter-cpp.
Implement a highlighting system using tree-sitter, supporting AST syntax highlighting for C++.
Specific advantages include cross-line string highlighting, recognition of escape sequences within strings,  colorful bracket matching and so on.
- cpp-ast-lang.scm : Records the highlighting colors for keywords and different token types.
- lang_parser.h & lang_parser.cpp : Programming language parser; uses tree-sitter to compile code and obtain an AST, and then retrieves a series of tokens and their corresponding attributes from the AST.
- ast_language.cpp : Performs compilation operations using ``advance`` and obtains the color for corresponding tokens using ``get_color``.
## Why
The old lexical highlighting could not distinguish many highlighting situations.
<img width="505" alt="Compare" src="https://github.com/user-attachments/assets/2eabbbd1-f48b-4179-9d0b-acad4787af90">

## How to test your changes?
1. Build and run.
2. Turn on"Edit" -> "Preference" -> "Other" -> "AST syntax highlighting".
3. New cpp code blocks and code lines will use AST syntax highlighting.
4. AST syntax highlighting can be turned off at any time.

2024-08-07 09:26 UTC, jingkaimori commented
if embed code contains three dot like this, the render will be corrupted:
```cpp
template<class T>
void function(T a, T b){
    // three dots here corrupts the next function ...
};

function((char)a, (int)b);
```

2024-08-07 11:02 UTC, da-liii commented
@jingkaimori 我们需要思考一下，如何在接口层面规避到Cork编码，特别是代码模式。努力规避Cork编码这件事，应该由我们开发者完成，而不是让OSPP开发者完成。因为这块挺复杂，挺关键的。

2024-08-07 12:56 UTC, jingkaimori commented
> 如何在接口层面规避到Cork编码，特别是代码模式。

非常难，如果不在ast树处理这块处理Cork，而是在更前的环节处理的话：要么从文档树里拿到的子树可能是utf8编码；要么就只是简单地把utf8_to_cork移到typeset里，还会影响别的language。

这个问题的本质是，在当前的字典下`utf8_to_cork(cork_to_utf8(str))`不一定等于源字符串`str`。但是不处理也不行，文档的叶子节点里左尖括号都是用`<gtr>`表示，而尖括号的映射和三个点的映射在同一个字典里。得想办法甩掉目前的converter

2024-08-07 13:55 UTC, da-liii commented on src/System/Language/ast_language.cpp
> +      string tokentype= get_label (group_of[j]);
tokentype的命名风格和别的地方不一致

2024-08-07 13:56 UTC, da-liii commented on src/System/Language/ast_language.cpp
> +  for (i= 1; i < N (s); i++)
这里每次循环都会调用 N(s)，建议使用 int s_N= N(s)，然后使用 s_N 代替 N(s)

2024-08-07 13:58 UTC, da-liii commented on xmake/packages.lua
> +    add_requires("tree-sitter-cpp "..TREESITTER_CPP_VERSION, {configs = {shared = true}, system=false})
这里的动态链接库，有很多细节需要处理，特别是涉及安装包的制作。

2024-08-07 14:00 UTC, da-liii commented on xmake/packages.lua
> +    add_requires("tree-sitter-cpp "..TREESITTER_CPP_VERSION, {configs = {shared = true}, system=false})
这里的代码需要考虑打包的时候，动态链接库放在什么地方，在不同的系统上需要验证

具体是在 research target 的 install 的时候，需要把动态链接库安装到合适的位置

2024-08-07 14:02 UTC, UnbSky commented on src/System/Language/ast_language.cpp
> +  for (i= 1; i < N (s); i++)
这个直接抄的prog_language.cpp里写的这个函数

2024-08-07 14:05 UTC, da-liii commented on src/System/Language/ast_language.cpp
> +  for (i= 1; i < N (s); i++)
那里面也要改一下，一开始没注意这块的性能。新增的代码尽可能是最好的状态

2024-08-07 14:08 UTC, da-liii commented on xmake/research.lua
> +    add_packages("tree-sitter")
可以设置编译开关，决定是否引入

2024-08-07 14:12 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.cpp
> +  for (int i= 0; i < N (root); i++) {
N(root)需要使用 int root_N= N(root); 然后使用 root_N

2024-08-07 14:13 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.cpp
> +    if (root[i]->op == 807) {
807这个magic number是什么意思？是某个tree-label?

2024-08-07 14:21 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.cpp
> +    if (root[i]->op == 807) {
NBSP 节点 op=807, 改成宏了

2024-08-07 14:25 UTC, da-liii commented
如果是选择每一个编程语言的高亮插件都作为动态链接库引入，那么建议采用编译时的开关。这样做工作量大一些。

目前采用的是运行时的开关，这样做的话，建议直接将 tree-sitter-cpp 作为静态链接库引入。

可以后续再做相关优化。src/Plugins下面的都是C++插件，是需要能通过编译开关选择不引入的。

2024-08-07 14:38 UTC, UnbSky commented
> 如果是选择每一个编程语言的高亮插件都作为动态链接库引入，那么建议采用编译时的开关。这样做工作量大一些。
> 
> 目前采用的是运行时的开关，这样做的话，建议直接将 tree-sitter-cpp 作为静态链接库引入。
> 
> 可以后续再做相关优化。src/Plugins下面的都是C++插件，是需要能通过编译开关选择不引入的。

我先改回静态库，后续如果有问题和需求可以再详细讨论，我现在还不了解你们是如何处理动态链接库的。

2024-08-07 16:14 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +  (:require (and (== lan "cpp-ast") (== key "white_theme")))
dark theme: 深色模式
light theme: 浅色模式

2024-08-07 16:17 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.hpp
> +#define NBSP_OP 807
为什么 NBSP_OP 是 807? 这个是在调试的是否发现的吧？这个值受什么影响，是否稳定？

这里需要说明一下，这个细节蛮重要的，如果哪一天NBSP_OP不是807，而是808，那代码就出错的

2024-08-07 16:18 UTC, da-liii commented on src/System/Language/prog_language.cpp
> +    // cout << "operator_parser:" << oper << " " << start << " " << end << "\n";
这三行的更改和这个pr无关，，需要恢复成原来的样子

2024-08-07 16:21 UTC, da-liii commented
这个pr没有提供一些关键的测试用例，测试用例都放在：
https://github.com/XmacsLabs/mogan/tree/branch-1.2/TeXmacs/tests/tmu

可以放在单个tmu里面，比如 TeXmacs/tests/tmu/70_2.tmu

测试用例需要挑选一些关键的用例，代码量越少越好

2024-08-07 16:24 UTC, da-liii commented on src/System/Language/prog_language.cpp
> +  // cout << use_modules << "\n";
这一行清理一下

2024-08-07 16:25 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (string_quate
quate 这个拼写有问题，应该是 quote

2024-08-07 16:25 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (preprocess
这个是动词，和别的地方风格不统一，应该是 preprocessor

2024-08-07 16:29 UTC, da-liii commented on src/System/Language/impl_language.hpp
> + * COPYRIGHT  : (C) 1999-2020  Joris van der Hoeven, Darcy Shen, UnbSky
2020 -> 2024

2024-08-07 16:36 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.hpp
> +#define NBSP_OP 807
稳定，如果你认为你需要经常修改NBSP对应的op值，可以给出解决方案。

2024-08-07 17:15 UTC, UnbSky commented
> 这个pr没有提供一些关键的测试用例，测试用例都放在： https://github.com/XmacsLabs/mogan/tree/branch-1.2/TeXmacs/tests/tmu
> 
> 可以放在单个tmu里面，比如 TeXmacs/tests/tmu/70_2.tmu
> 
> 测试用例需要挑选一些关键的用例，代码量越少越好

已加测试用例TeXmacs/tests/tmu/70_2.tmu

2024-08-08 00:10 UTC, da-liii commented on src/System/Language/prog_language.cpp
> +
这个空行没有必要引入

2024-08-08 00:11 UTC, da-liii commented on xmake/packages/t/tree-sitter-cpp/port/xmake.lua
> +    add_headerfiles("bindings/c/tree-sitter-cpp.h")
最后添加一个空行

2024-08-08 00:11 UTC, da-liii commented on xmake/packages/t/tree-sitter-cpp/xmake.lua
> +    end)
最后添加一个空行

2024-08-08 00:36 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (string_quato
是 string_quote 吧？

2024-08-08 00:38 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +  (:require (and (== lan "cpp-ast") (== key "keytoken")))
这里的 lan，还是使用 define-format 里面定义的format，也就是 cpp，不需要在末尾添加 `-ast`

2024-08-08 00:41 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
Scheme中的十六进制数的语法是 `#x000000`

2024-08-08 00:48 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.cpp
> +  for (int i= 0; i < root_N; i++) {
i 这里只是为了 root[i]的话，可以用range_for

参考：
+ https://github.com/XmacsLabs/lolly/pull/327

2024-08-08 00:53 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.hpp
> +#define NBSP_OP 807
https://github.com/XmacsLabs/moebius/blob/main/moebius/tree_label.cpp#L31-L38

可以看这里，这个值应该是在 make_tree_label的时候构建出来的

原语的label的值是固定的，见 https://github.com/XmacsLabs/moebius/blob/main/moebius/tree_label.hpp

2024-08-08 00:54 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.hpp
> +#define NBSP_OP 807
> 稳定，如果你认为你需要经常修改NBSP对应的op值，可以给出解决方案。

这个值是不稳定的，原语的数量的增删会导致这个值的变化，我们需要找到一种合理的方式，从string格式的label得到具体的数值

2024-08-08 00:55 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.hpp
> +#endif // defined LANG_PARSER_H
最后加一个空行

2024-08-08 00:55 UTC, da-liii commented on src/System/Language/ast_language.cpp
> +}
最后加一个空行

2024-08-08 00:56 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#BF2C2C "escape_sequence" "system_lib_string")
这个设计不错，这样这些identifier就是自定义的，而不是写死在C++代码里面

2024-08-08 01:39 UTC, UnbSky commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +  (:require (and (== lan "cpp-ast") (== key "keytoken")))
需要，创建新的ast_language_rep的时候进来的参数被改成了“cpp-ast”

2024-08-08 01:40 UTC, UnbSky commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
get_color的颜色显示返回的字符串，没有必要多一次转换

2024-08-08 01:56 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
那为什么不直接使用字符串 "#000000"

2024-08-08 01:57 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
要么字符串，要么16进制，目前这个 C# 开头的方案不合适

2024-08-08 01:58 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
然后，我认为用  `#000000` 的好处是，少写两个引号，只要在上层做一下数字到字符串的转换就可以了

2024-08-08 02:37 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.hpp
> +#define NBSP_OP 807
NBSP结点没有label, 或者说N(label) = 0,已添加测试cout位置

2024-08-08 02:57 UTC, UnbSky commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
这里需要一个symbol, 换成其他的会报错

2024-08-08 03:18 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +  (:require (and (== lan "cpp-ast") (== key "keytoken")))
你可以在创建的时候，只传过来 `cpp` 。这里可以和原来的保持一致，这样做迁移的时候，工作量可以小一些

2024-08-08 03:37 UTC, UnbSky commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +  (:require (and (== lan "cpp-ast") (== key "keytoken")))
language::instances 依赖该参数，不可更改，否则会导致重复创建实例，目前通过修改ast_language_rep构造函数来满足该需求

2024-08-08 04:32 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.hpp
> +#define NBSP_OP 807
可以用`make_tree_label("nbsp")`获得对应的`tree_label`编号

2024-08-08 04:45 UTC, da-liii commented on TeXmacs/tests/tmu/70_11.tmu
> +</initial>
这个最后一个换行，我们可以在tmu里面改进一下

2024-08-08 05:18 UTC, UnbSky commented on TeXmacs/tests/tmu/70_11.tmu
> +</initial>
一保存换行就没了，现在手动加了一个换行

2024-08-08 05:21 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.hpp
> +#define NBSP_OP 807
> 可以用`make_tree_label("nbsp")`获得对应的`tree_label`编号

已改，目前在ast_language_rep的advance函数中执行make_tree_label("nbsp")一次获得编号，该编号后续传参进入lang_parser。

2024-08-08 05:38 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
实测：
```
`(light_theme
  (#x000000 "none"))

`(light_theme ("#000000" "none"))
```
上述两种方案都是可以的

2024-08-08 05:43 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
```
(string-append "#" (integer->padded-hexadecimal #x000000 6))
```
用上述代码就可以吧数字 `#x000000` 变成字符串 `"#000000"`

2024-08-08 05:43 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
我建议采用：
```
`(light_theme ("#000000" "none"))
```
这样在C++里面不用改代码

2024-08-08 05:46 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
你说的出错在这里：
![image](https://github.com/user-attachments/assets/6691b068-6895-430b-9773-aec06272cc0d)

其实可以直接规避 tm->tree 的转换，可以说，之前在 prog_language.cpp 写的代码是错误的

2024-08-08 05:47 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
应该用`stree->tree`而不是`tm->tree`:
![image](https://github.com/user-attachments/assets/8e8069fa-53f0-462b-bf04-3f94a739c001)

2024-08-08 05:49 UTC, da-liii commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
![image](https://github.com/user-attachments/assets/e56fab60-f1cc-4b9c-a62a-439edbd1401a)

这个截图里面信息更全一些

2024-08-08 06:08 UTC, UnbSky commented on TeXmacs/plugins/code/progs/code/cpp-ast-lang.scm
> +    (C#000000 "none")
已改为stree->tree，颜色已改为"#000000"格式

2024-08-08 06:28 UTC, da-liii commented
LGTM on the interface part and code styles

2024-08-08 08:05 UTC, jingkaimori reviewed
不少细节还有提升空间

2024-08-08 08:05 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.cpp
> +  string_u8 code     = "";
我看pr里通过计算拼接好的代码`code`和树结构`tag`来计算`ast_language::advance`树参数的哈希。如果采用上一个评论里提到的api算，`code`和`tag`我感觉都没必要保留。

2024-08-08 08:54 UTC, jingkaimori requested changes
现在基于字符串拼接的处理虽然能用，但是还是有点小毛病：
- 字符串treesitter接受的唯一一种输入形式，而字符串拼接有潜在的性能问题
- 用字符串表示`TSNode`节点的类型也不是那么恰当
- 检查树是不是已经解析过了的哈希部分，也值得改进。

这个pr虽然实现了功能，达到了合并的最低标准，但是距离最简洁的实现还有相当的距离，如果应用这几项修改，代码的结构也许会大变，因此我不赞成合并目前这个pr。考虑到ospp一个月后要结束，如果时间赶不上，合并这一版也不是不行。

2024-08-08 08:54 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.cpp
> +    const char*   node_type = ts_node_type (leaf_node);
tree-sitter里，节点的类型既能用字符串表示，又能用类型ID表示。由于操作整数类型的ID性能肯定优于操作字符串，你看看能不能在代码里用类型ID表示类型？

https://github.com/tree-sitter/tree-sitter/blob/7583d394b41a9ab26ae6d52d51c8965f627996cd/lib/include/tree_sitter/api.h#L442-L450

2024-08-08 08:54 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.cpp
> +    string    code_fragment_cork  = utf8_to_cork (code_fragment);
代码块也许不需要从拼接好的字符串上取，通过行号和列号从`ast_language::advance`的树参数上取怎么样？

2024-08-08 08:54 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.cpp
> +      ts_parser_parse_string (ast_parser, NULL, source_code, N (code));
这一块有没有可能不去拼接字符串，而是用输入函数的方式，从tree里逐个提取字符？
https://github.com/tree-sitter/tree-sitter/blob/7583d394b41a9ab26ae6d52d51c8965f627996cd/lib/include/tree_sitter/api.h#L74-L78
https://github.com/tree-sitter/tree-sitter/blob/7583d394b41a9ab26ae6d52d51c8965f627996cd/lib/include/tree_sitter/api.h#L223-L270

2024-08-08 08:55 UTC, UnbSky commented on src/System/Language/ast_language.cpp
> +  string_u8 code=
hash(tree) 可行而且高效简洁, nbsp_op目前不需要再传入lang_parser,tag可以移除,code和code_u8区分暂时还需要,不过code应该也可以后续优化掉。

2024-08-08 09:00 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.cpp
> +                                 int& start_index, int nbsp_op) {
已移动至ast_language构造函数中

2024-08-08 09:05 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.cpp
> +      ts_parser_parse_string (ast_parser, NULL, source_code, N (code));
这需要进一步讨论和研究

2024-08-08 09:09 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.cpp
> +    const char*   node_type = ts_node_type (leaf_node);
理论上应该可以，如果操作字符串非常耗时，该处修改会很有必要，不然可能这里的优化有点多余。

2024-08-18 03:47 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.cpp
> +    string    code_fragment_cork  = utf8_to_cork (code_fragment);
tree-sitter的列号基于utf-8编码，取字符串还是需要转换，省不了时间空间

2024-08-18 03:49 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.cpp
> +      ts_parser_parse_string (ast_parser, NULL, source_code, N (code));
研究结果表明，`O(长度)`的复制和转换避免不了，转换结果也得存储，就这样吧

2024-08-18 10:59 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.cpp
> +    const char*   node_type = ts_node_type (leaf_node);
已将lang_parser中的token_type格式从string改为TSSymbol

2024-08-19 13:26 UTC, jingkaimori reviewed
提一些细节问题

2024-08-19 13:26 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.hpp
> +  list<int>      token_lang_pros;
[`array`结构也可以从后面添加元素](https://xmacslabs.github.io/lolly/array_8hpp_source.html)，而且大部分情况下`array`更快。因为随机访问`list`的元素时，会遍历每一个元素；向`list`逐个添加元素的时候，分配内存的次数肯定多于`array`。

2024-08-19 13:26 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.hpp
> +  list<int>      token_lang_pros;
[`array`结构也可以从后面添加元素](https://xmacslabs.github.io/lolly/array_8hpp_source.html)，而且大部分情况下`array`更快。因为随机访问`list`的元素时，会遍历每一个元素；向`list`逐个添加元素的时候，分配内存的次数肯定多于`array`。

2024-08-19 13:26 UTC, jingkaimori commented on src/Plugins/Treesitter/lang_parser.hpp
> +  int       large_bracket_depth= 0; // depth of {}
这个depth应该不会小于0，可以用无符号整数类型

2024-08-19 15:37 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.hpp
> +  int       large_bracket_depth= 0; // depth of {}
这个问题应该还好，没啥问题

2024-08-19 15:37 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.hpp
> +  list<int>      token_lang_pros;
list很慢的，这里不应该用list

2024-08-19 15:40 UTC, da-liii commented on src/Plugins/Treesitter/lang_parser.cpp
> +  const char* source_code= as_charp (code_string); // code
现在用 as_charp的地方不多了，大部分我都已经改掉了

2024-08-20 02:31 UTC, da-liii commented on src/System/Language/ast_language.cpp
> +  tree&  my_father (subtree (the_et, reverse (obtain_ip (t)->next)));
my_father这个命名需要改一下，比如 father_node

2024-08-20 02:34 UTC, da-liii commented on src/System/Language/impl_language.hpp
> +  int                     nbsp_op;
这个应该是在需要的时候，临时获得，而不是放在成员变量里面

2024-08-20 02:46 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.cpp
> +  const char* source_code= as_charp (code_string); // code
已改，建议添加注释某些函数已被废弃

2024-08-20 02:47 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.hpp
> +  list<int>      token_lang_pros;
list确实很慢，改成array之后速度快很多，我还以为这个list和std::vector一样随机访问是N(1)

2024-08-20 02:49 UTC, UnbSky commented on src/System/Language/impl_language.hpp
> +  int                     nbsp_op;
> 也许`nbsp_op`这个参数不需要到处流浪，这个参数应该会随着样式文件的加载/卸载而变化，大概率在`ast_language`的整个生命周期里都不变。可以考虑把这个参数做成`lang_parser`的属性字段。

之前还说作为属性字段呢，怎么又要临时获得了？

2024-08-20 03:37 UTC, UnbSky commented on src/Plugins/Treesitter/lang_parser.cpp
> +  barcket_symbol_list << ts_language_symbol_for_name (ts_lang, "}", 1, false);
已放入scm中，可自行设置需要匹配的括号组，和对应匹配括号组颜色循环的周期

2024-08-20 06:06 UTC, jingkaimori commented on src/System/Language/impl_language.hpp
> +  int                     nbsp_op;
> 这个应该是在需要的时候，临时获得，而不是放在成员变量里面

tree_label是初始化后就不变的吧，没必要临时获取

2024-08-20 17:36 UTC, UnbSky commented
目前给出一个判断部分typeset中的tree来获得代码根节点的方案，不再依赖the_et，可以修复AST高亮的”复制到图片“问题，获得手段不会对原本的typeset产生太大的影响。

1. bridge_compound_rep::my_typeset可以在正常渲染advance的时候截获代码节点
2. concater_rep::typeset截获"复制到图片"的第一次advance代码节点
3. make_lazy_compound截获"复制到图片"的第二次advance代码节点
原本在"复制到图片"无法获得获得代码节点和IP错误的原因是由于print_snippet导致两次调用的advance中, 第一次调用advance的ip是相对于传入print_snippet的选中部分tree的，第二次调用advance的ip则是由于make_lazy函数的调用导致ip不符合期望，两次截获的结点相对于传入advance的结点的IP是相对正确的，因此整个修复方式只需要获得代码节点。

2024-08-21 05:22 UTC, jingkaimori approved these changes
LGTM, tweaking may be added in separate pr

2024-08-21 05:22 UTC, merged