[81_8] Beautify tabbar style on linux and windows
XmacsLabs/mogan pull request #2035
Opened 2024-08-25 05:59 UTC by Minzihao

## What
Beautify tabbar style on linux and windows

## How to test your changes?
现在在windows上看起来如下，这是参考linux的Dolphin文件浏览器配色，所以在linux上看起来应该也差不多 @da-liii 先看看目前的效果，ok的话再加上深色主题的配色。另外目前tab上的关闭按钮也（好像）有点突兀，觉得丑的话后面也改。
![2024-08-25135226-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/6f917bf0-5200-4cdb-b7a7-951c41dcf9b5)

2024-08-25 09:25 UTC, da-liii commented
关闭标签页的按钮的颜色逻辑反了，应该默认和标签底色一样，当光标悬浮其上时，颜色调整为亮色。

2024-08-25 15:13 UTC, Minzihao commented
> 关闭标签页的按钮的颜色逻辑反了，应该默认和标签底色一样，当光标悬浮其上时，颜色调整为亮色。
> 
> 这是Dolphin里面，光标悬浮在标签页的悬浮按钮是，会显示为红色，默认的时候，不会那么明显（底色和标签的底色一致）： ![image](https://private-user-images.githubusercontent.com/1267865/361198896-b5b996de-d72e-4866-98e4-c60074c35f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTgzMzYsIm5iZiI6MTcyNDU5ODAzNiwicGF0aCI6Ii8xMjY3ODY1LzM2MTE5ODg5Ni1iNWI5OTZkZS1kNzJlLTQ4NjYtOThlNC1jNjAwNzRjMzVmMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTUwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA0MWZlNzNlMWU4NmRhZmJiNzUzNTZhOTEzMWFiMDYyM2I1ZTIyNmE5N2E2NDVkYzU2YTgwYzUwZDlkYWI2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wy4eKsJY-2JRAwrcUQ9MFm8uOavohcGaNtVw9XwQMUk)

改好了

2024-08-25 15:30 UTC, Oyyko commented
<img width="974" alt="image" src="https://github.com/user-attachments/assets/21f47953-fd3b-4064-8877-5ecaecd76feb">
mac上效果还行

2024-08-25 15:44 UTC, Minzihao commented
现在再试试看 @da-liii @Oyyko

2024-08-25 21:03 UTC, Oyyko commented
<img width="854" alt="image" src="https://github.com/user-attachments/assets/893d4869-01d8-4101-a547-b7081a38682f">
@da-liii 有个和这个PR无关的问题。我在mac上面编译运行之后，进入一个空文档，然后打一个字就会出现这个报错。

2024-08-25 21:03 UTC, Oyyko commented
@Minzihao 我们有计划在未来优化一下关闭标签页的时候的效果吗？就是目前还是会有一些延迟。

2024-08-25 21:10 UTC, Oyyko commented on src/Plugins/Qt/QTMTabPage.cpp
> +  QString qss, bgColor, bgColorHover, borderColor, borderColorTop;
变量名可以改为使用下划线格式？

2024-08-25 21:10 UTC, Oyyko commented on src/Plugins/Qt/QTMTabPage.cpp
> +  parentWidget ()->setFixedHeight (h + 2);
常量，例如这里的2，可以改为constexpr变量吗？有一个变量名比较好

2024-08-25 21:10 UTC, Oyyko commented on src/Plugins/Qt/QTMTabPage.cpp
> +}
这一段可以打包成一个函数？

2024-08-25 21:10 UTC, Oyyko commented on src/Plugins/Qt/QTMTabPage.cpp
> +}
51到80行

2024-08-26 02:22 UTC, Minzihao commented on src/Plugins/Qt/QTMTabPage.cpp
> +#ifdef Q_OS_LINUX || Q_OS_MAC
改成 `#if defined(Q_OS_LINUX) || defined(Q_OS_MAC)`没问题了

2024-08-26 02:22 UTC, Minzihao commented on src/Plugins/Qt/QTMTabPage.cpp
> +  QString qss, bgColor, bgColorHover, borderColor, borderColorTop;
ok

2024-08-26 02:23 UTC, Minzihao commented on src/Plugins/Qt/QTMTabPage.cpp
> +  parentWidget ()->setFixedHeight (h + 2);
ok

2024-08-26 02:23 UTC, Minzihao commented on src/Plugins/Qt/QTMTabPage.cpp
> +}
ok

2024-08-26 02:26 UTC, Minzihao commented
> @Minzihao 我们有计划在未来优化一下关闭标签页的时候的效果吗？就是目前还是会有一些延迟。

在下一个pr试试看

2024-08-26 02:27 UTC, Minzihao commented
> X没有在垂直方向上居中

看看现在X有没有在垂直方向上居中🤦‍

2024-08-26 02:43 UTC, da-liii commented
> 我在mac上面编译运行之后，进入一个空文档，然后打一个字就会出现这个报错。

@Oyyko 这是故意的，可以关闭的（在弹出的窗口的Preferences里面），我认为这是一个bug，需要修复

2024-08-26 03:21 UTC, da-liii commented
> 看看现在X有没有在垂直方向上居中

还是有问题，你可以在wsl debian 12里面做相关测试，现在的wsl也是支持图形界面的

2024-08-26 15:07 UTC, da-liii commented
我改了`QTMTabPage::resizeEvent (QResizeEvent* e) {`里面的y值，发现红色的背景和X是一起的，应该是需要在QSS里面搞定
```
  int y= e->size ().height () / 2 - h/2;
```

2024-08-26 15:14 UTC, Minzihao commented
> 我改了`QTMTabPage::resizeEvent (QResizeEvent* e) {`里面的y值，发现红色的背景和X是一起的，应该是需要在QSS里面搞定
> 
> ```
>   int y= e->size ().height () / 2 - h/2;
> ```

应该是内置padding的问题

2024-08-26 15:15 UTC, Minzihao commented
> wsl debian 12

不知道什么是wsl debian 12🤦‍

2024-08-26 15:16 UTC, da-liii commented
![image](https://github.com/user-attachments/assets/f64eced6-e33b-40ec-a318-0d037ca443e2)

换了个字：口，背景的红色没问题

2024-08-26 15:19 UTC, da-liii commented on TeXmacs/progs/texmacs/menus/tabpage-menu.scm
> +        ((balloon "⨉" "Close") (safely-kill-buffer-by-url buf))
换成🗙之后，垂直居中没问题了

2024-08-26 15:19 UTC, Minzihao commented on TeXmacs/progs/texmacs/menus/tabpage-menu.scm
> +        ((balloon "⨉" "Close") (safely-kill-buffer-by-url buf))
文字玄学

2024-08-26 15:21 UTC, Minzihao commented on TeXmacs/progs/texmacs/menus/tabpage-menu.scm
> +        ((balloon "⨉" "Close") (safely-kill-buffer-by-url buf))
但是在windows就不居中了，最好还是搞一个图片吧，xpm图片怎么做的

2024-08-26 15:23 UTC, da-liii requested changes
使用✕解决字体垂直方向居中的问题

2024-08-26 15:23 UTC, da-liii commented on TeXmacs/progs/texmacs/menus/tabpage-menu.scm
> +        ((balloon "⨉" "Close") (safely-kill-buffer-by-url buf))
见：https://segmentfault.com/q/1010000042611231

编号为 2715这个unicode，蛮好的：https://symbl.cc/cn/2715/

2024-08-26 15:25 UTC, da-liii commented on TeXmacs/progs/texmacs/menus/tabpage-menu.scm
> +        ((balloon "⨉" "Close") (safely-kill-buffer-by-url buf))
你试试 2715 这个字符在Windows上行不行？

2024-08-26 15:27 UTC, Minzihao commented on TeXmacs/progs/texmacs/menus/tabpage-menu.scm
> +        ((balloon "⨉" "Close") (safely-kill-buffer-by-url buf))
这个好，没有问题
![image](https://github.com/user-attachments/assets/4c0e7567-5a5b-45c3-aab6-418510e26d53)

2024-08-26 15:57 UTC, da-liii approved these changes

2024-08-26 16:03 UTC, merged