use ust to get stacktrace with line number
XmacsLabs/mogan pull request #344
Opened 2022-10-12 09:04 UTC by PikachuHy

ust GitHub repo

https://github.com/MisterTea/UniversalStacktrace

MacOS only

```

Backtrace of C++ stack:
[0] 0x1038dd3aa get_stacktrace(unsigned int) (stack_trace.cpp:23)
[1] 0x10392e899 get_crash_report(char const*) (tm_debug.cpp:131)
[2] 0x103ec7602 QTMWidget::resizeEvent(QResizeEvent*) (QTMWidget.cpp:217)
[3] 0x105d606b0 QWidget::event(QEvent*)
[4] 0x105dfaabb QFrame::event(QEvent*)
[5] 0x103eb5e8b QTMScrollView::surfaceEvent(QEvent*) (QTMScrollView.cpp:245)
[6] 0x103eb6029 QTMSurface::event(QEvent*) (QTMScrollView.cpp:43)
[7] 0x105d0dda7 QApplicationPrivate::notify_helper(QObject*, QEvent*)
[8] 0x105d0ed63 QApplication::notify(QObject*, QEvent*)
[9] 0x102f46385 QTMApplication::notify(QObject*, QEvent*) (QTMApplication.hpp:149)
[10] 0x106e5d3ba QCoreApplication::notifyInternal2(QObject*, QEvent*)
[11] 0x105d5d4f2 QWidgetPrivate::setGeometry_sys(int, int, int, int, bool)
[12] 0x105d5d5be QWidget::resize(QSize const&)
[13] 0x105d56b9b QWidget::setMinimumSize(int, int)
[14] 0x105d573b4 QWidget::setMinimumHeight(int)

......
```

2022-10-12 09:54 UTC, PikachuHy commented
rather slow
```
11/19 Test #11: list_test ........................   Passed   11.33 sec
```

2022-10-12 11:31 UTC, darcy-shen commented on src/Plugins/UniversalStacktrace/ust/ust.hpp
> +#pragma once
Two necessary info:
+ LICENSE and Author
+ the original repo and the commit id

2022-10-12 11:32 UTC, darcy-shen requested changes
Need more info of ust

2022-10-14 17:29 UTC, darcy-shen commented on src/Plugins/UniversalStacktrace/ust/ust.hpp
> +#pragma once
could you add these info to a README.md under src/Plugins/UniversalStacktrace

2022-10-15 05:06 UTC, PikachuHy commented on src/Plugins/UniversalStacktrace/ust/ust.hpp
> +#pragma once
sure

2022-10-15 09:04 UTC, darcy-shen approved these changes

2022-10-15 09:05 UTC, merged