add package mac ci
XmacsLabs/mogan pull request #366
Opened 2022-11-02 13:28 UTC by PikachuHy

2022-11-02 15:00 UTC, darcy-shen requested changes

2022-11-02 15:00 UTC, darcy-shen commented on .github/workflows/package-macos.yml
> +      - name: Compress
dmg is produced by `macdeployqt`

2022-11-02 15:01 UTC, darcy-shen commented on .github/workflows/package-macos.yml
> +      - name: Compress
I guess that you should run `packages/macos/package.sh` locally step by step on macOS to understand what happened.

2022-11-03 14:44 UTC, PikachuHy commented
```
cp /Applications/TeXmacs.app/Contents/Resources/share/TeXmacs/bin/gs Mogan.app/Contents/Resources/share/Xmacs/bin/
cp /Applications/Mogan.app/Contents/Resources/share/Xmacs/plugins/eukleides/bin/eukleides Mogan.app/Contents/Resources/share/Xmacs/plugins/eukleides/bin
```

why gs and eukleides not include on Mogan repo?

2022-11-03 14:52 UTC, darcy-shen commented
For gs, see https://github.com/XmacsLabs/mogan/issues/294

For Eukleides, it is a plugin, we should maintain it outside Mogan Editor.

2022-11-05 11:39 UTC, darcy-shen approved these changes
LGTM

2022-11-05 11:39 UTC, merged