[8_1] add windows installer and corresponding ci
XmacsLabs/mogan pull request #764
Opened 2023-06-29 02:55 UTC by jingkaimori

This pull request add windows packager description file for Qt installer framework.

TODO:
[ ] Detect and remove legacy app installed by inno setup.
[ ] Translate installer

2023-06-30 16:27 UTC, darcy-shen commented on packages/windows/packages/org.xmacslabs.mogan/meta/package.in.xml
> +<?xml version="1.0" encoding="UTF-8"?>
目录有问题:
```
org.xmacslabs.mogan -> app.mogan
```

2023-07-01 13:50 UTC, darcy-shen commented
> Adjust icon

这个后面再换，我们先把ci做起来，这样这些代码后面可以放到texmacs官方的仓库里面

2023-07-02 13:31 UTC, darcy-shen commented on .github/workflows/ci-xmake-windows.yml
> +          name: mogan-windows-nightly-installer.exe
这个地方上传之后，默认是zip压缩包，实际上不是exe

2023-07-02 13:34 UTC, darcy-shen commented
第二个问题：
我选择了`C:/Program Files`为安装目录，检测到Mogan这个目录已经有内容了，它直接把所有内容安装到了Mogan的上一层目录，即直接在C盘解压了

2023-07-02 13:39 UTC, darcy-shen commented
第三个问题：卸载的时候，17个操作，卡在了第十六个操作上：
![image](https://github.com/XmacsLabs/mogan/assets/1267865/b298169a-3d11-472e-bb55-574e6ccae592)

```
正在移除从“1.2.0share.7z”中提取的文件
正在移除从“1.2.0bin.7z”中提取的文件
正在移除从“1.2.0progs.7z”中提取的文件
正在移除从“1.2.0misc.7z”中提取的文件
正在移除从“1.2.0plugins.7z”中提取的文件
正在移除从“1.2.0styles.7z”中提取的文件
正在移除从“1.2.0content.7z”中提取的文件
正在移除从“1.2.0examples.7z”中提取的文件
正在移除从“1.2.0langs.7z”中提取的文件
正在移除从“1.2.0fonts.7z”中提取的文件
正在移除从“1.2.0doc.7z”中提取的文件
正在移除从“1.2.0packages.7z”中提取的文件
正在移除从“1.2.0texts.7z”中提取的文件
```

2023-07-02 14:29 UTC, jingkaimori commented
> 第二个问题： 我选择了`C:/Program Files`为安装目录，检测到Mogan这个目录已经有内容了，它直接把所有内容安装到了Mogan的上一层目录，即直接在`C:/Program Files`解压了
未能复现，如果在安装有旧版本墨干的目录中安装新版本墨干，原有的文件不会被覆盖

2023-07-02 14:31 UTC, jingkaimori commented
> 第三个问题：卸载的时候，17个操作，卡在了第十六个操作上：

未能复现，推测为注册表问题，查找和`tm`相关的注册表项

2023-07-02 14:39 UTC, darcy-shen commented
> 未能复现，推测为注册表问题，查找和`tm`相关的注册表项

这里卡住的原因是: 这个卸载工具直接把`C:/Program Files/`下面所有的文件都删除了。我已经看到我安装的GNU Octave已经残缺不全了。
所以，不应该让用户安装到`C:/Program Files/`，而应该是`C:/Program Files/Mogan`

2023-07-02 14:40 UTC, darcy-shen requested changes
默认安装目录，以及安装目录的切换这块需要修复

2023-07-03 07:32 UTC, merged