[23_11] Offset the pasted object
XmacsLabs/mogan pull request #783
Opened 2023-07-09 18:29 UTC by Oyyko

2023-07-10 13:27 UTC, darcy-shen commented on TeXmacs/progs/graphics/graphics-utils.scm
> +    '(point "0" "0")))
最后加一个空格

2023-07-10 13:38 UTC, darcy-shen commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (get-x-from-point pt)
point-get-x 会更好，因为url相关的函数是`url-*`，string相关的函数是`string-*`

2023-07-10 13:38 UTC, darcy-shen commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (get-y-from-point pt)
point-get-y

2023-07-10 13:40 UTC, darcy-shen commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (add-two-points pt1 pt2)
points-add

2023-07-10 13:55 UTC, darcy-shen commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (get-sum-point obj)
get-sum-point -> points-sum

2023-07-10 13:57 UTC, darcy-shen requested changes
第一次粘贴没问题了，第二次、第三次、第四次、第五次粘贴还是有问题。

2023-07-10 14:03 UTC, darcy-shen commented on TeXmacs/progs/graphics/graphics-group.scm
> +  (define (get-paste-offset-by-pos obj)
这个添加位移的策略，需要用单元测试来保证其正确性。测试用例至少有九种情况。

因为需要添加测试，所以这块可以放在外面，用 tm-define 来定义

2023-07-11 11:22 UTC, Oyyko commented on TeXmacs/progs/graphics/graphics-utils.scm
> +    '(point "0" "0")))
Fine.

2023-07-11 11:23 UTC, Oyyko commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (get-x-from-point pt)
Fine.

2023-07-11 11:23 UTC, Oyyko commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (get-y-from-point pt)
Fine.

2023-07-11 11:23 UTC, Oyyko commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (add-two-points pt1 pt2)
Fine.

2023-07-11 11:23 UTC, Oyyko commented on TeXmacs/progs/graphics/graphics-utils.scm
> +(tm-define (get-sum-point obj)
Fine.

2023-07-11 11:24 UTC, Oyyko commented
> 第一次粘贴没问题了，第二次、第三次、第四次、第五次粘贴还是有问题。

已修复。

2023-07-11 11:24 UTC, Oyyko commented on TeXmacs/progs/graphics/graphics-group.scm
> +  (define (get-paste-offset-by-pos obj)
已添加测试。

2023-07-11 12:49 UTC, darcy-shen commented
Tested on Windows, awesome work!

2023-07-11 12:49 UTC, merged