[50_1] refactor init_app
XmacsLabs/mogan pull request #914
Opened 2023-08-08 14:30 UTC by Oyyko

2023-08-08 14:36 UTC, darcy-shen commented on src/Texmacs/Server/tm_server.cpp
>    if (exists (my_init_file)) exec_file (my_init_file);
This is the init file provided by the user, it should also be put in init_app

2023-08-08 14:38 UTC, darcy-shen commented on src/Mogan/Research/research.cpp
> +    init_app (now_app);
init_app should be placed in the constructor of class server

and we can initialize in that way:
```
server sv(App::Draw)
```

2023-08-08 14:40 UTC, darcy-shen commented on src/Mogan/Research/research.cpp
> +enum class App { RESEARCH, DRAW };
`git grep enum`, you will find that the codestyle of enum in texmacs, in texmacs, we should use `enum class app`

2023-08-08 14:42 UTC, darcy-shen commented on src/Mogan/Research/research.cpp
> +      tm_init_file= "$TEXMACS_PATH/progs/init-texmacs-s7.scm";
how about rename it to `init-research.scm`

And the string `research`, `draw` could be generated via C++ enum.

See https://en.cppreference.com/w/cpp/language/enum

2023-08-08 14:43 UTC, darcy-shen commented on src/Mogan/Research/research.cpp
> -extern url    tm_init_file;
Note that there is a TeXmacs server mode. I guess that's why it is extern here.

2023-08-08 14:44 UTC, darcy-shen requested changes
Please make minimum changes to the codebase to support app type when initializing.

2023-08-09 01:18 UTC, Oyyko commented on src/Mogan/Research/research.cpp
> +      tm_init_file= "$TEXMACS_PATH/progs/init-texmacs-s7.scm";
I think that the reflection capabilities of C++ are currently insufficient to support the conversion of enum to texmacs string or C-style string. Additionally, if we were to use the texmacs string type here, we would be unable to achieve compile-time computing. But with C-style string, they cannot be added together in compile-time.

2023-08-09 01:23 UTC, Oyyko commented
Refactored. Please check if it is elegant.

2023-08-09 02:01 UTC, darcy-shen approved these changes

2023-08-09 04:38 UTC, merged